package com.sobhanbera.noisymelo.sobyte.model

enum class ScreenParams(val screenRouteName: String) {
	AUTH_NAVIGATION("AUTH_NAVIGATION"),
	LANDING_SCREEN("LANDING_SCREEN"),
	SIGN_IN_SCREEN("SIGN_IN_SCREEN"),
	SIGN_UP_SCREEN("SIGN_UP_SCREEN"),
	MAIN_APP_NAVIGATION("MAIN_APP_NAVIGATION"),
	MUSIC_PLAYER_SCREEN("MUSIC_PLAYER_SCREEN"),
	HOME_EXPLORE_SCREEN("HOME_EXPLORE_SCREEN"),
	SEARCH_SCREEN("SEARCH_SCREEN"),
	PROFILE_SCREEN("PROFILE_SCREEN"),
	SETTING_SCREEN("SETTING_SCREEN"),
	EDIT_PROFILE_SCREEN("EDIT_PROFILE_SCREEN"),
}